# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75349b51f875e9685f6495483f6b6dc371852885144f722f2ae1ffb6bcb78ae49fa2961b983bae20baa8bb2ce1c43f436ce52f2963357d12c23837caed17d9f5

test:
  secret_key_base: 2236caaabc8bf033b3a356f07259d82dd8680c8cd32dcb53ec8262a57a115e561d205049f1ad8893e93f4b9de11d4d669da00444941451d51bf8f54b7b922c23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
